routes/web.php
<?php
// use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('surat', 'SuratController');

Route::resource('rt', 'RTController');

Route::resource('rw', 'RWController');

Route::resource('penduduk', 'PendudukController');
Route::get('carikota/{id}', 'PendudukController@cariKota')->name('penduduk.carikota');
Route::get('carikecamatan/{id}', 'PendudukController@cariKecamatan')->name('penduduk.carikecamatan');
Route::get('carikelurahan/{id}', 'PendudukController@cariKelurahan')->name('penduduk.carikelurahan');
Route::get('carirw/{id}', 'PendudukController@cariRW')->name('penduduk.carirw');
Route::get('carirt/{id}', 'PendudukController@cariRT')->name('penduduk.carirt');

Route::resource('gambar', 'ImageController');

app/Models/Gambar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Gambar extends Model
{
    protected $table = 'gambar';
    protected $fillable = [
        'id', 'nama_file'
    ];
}

resources/views/gambar/create.blade.php
@extends('layouts.master')

@section('title', 'Gambar')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Form Input @yield('title')</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('gambar.store') }}" method="post" enctype="multipart/form-data" class="form-horizontal"> 
                    {{ csrf_field() }}
                    <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Gambar</label>
                            </div>
                            <div class="col">
                                <img id="preview" height="150px" src="{{ asset('images/nopic.jpg') }}">
                            </div>
                        </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="text-input" class=" form-control-label">Upload Gambar</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="file" name="photo" id="photo" onchange="readURL(this);" class="form-control-file">
                        </div>
                    </div>
                    <div class="menudata">
                        <button type="submit" value="upload" class="btn btn-primary btn-sm"><i class="fa fa-dot-circle-o"></i> Upload </button>
                        <a href="{{ route('gambar.index') }}" class="btn btn-danger btn-sm"><i class="fa fa-ban"></i> Batal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                jQuery('#preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
@endsection

resources/views/gambar/edit.blade.php
@extends('layouts.master')

@section('title', 'Gambar')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Form Edit @yield('title')</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('gambar.update', $gambar->id) }}" method="post" enctype="multipart/form-data" class="form-horizontal"> 
                    @method('put')
                    {{ csrf_field() }}
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="text-input" class=" form-control-label">Gambar</label>
                        </div>
                        <div class="col">
                            <img id="preview" height="150px" src="{{ url('/storage/photos/'.$gambar->nama_file) }}">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="text-input" class=" form-control-label">Upload Gambar</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="file" name="photo" id="photo" onchange="readURL(this);" class="form-control-file">
                        </div>
                    </div>
                    <div class="menudata">
                        <button type="submit" value="upload" class="btn btn-primary btn-sm"><i class="fa fa-dot-circle-o"></i> Upload </button>
                        <a href="{{ route('gambar.index') }}" class="btn btn-danger btn-sm"><i class="fa fa-ban"></i> Batal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                jQuery('#preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
@endsection

resources/views/gambar/index.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/lib/datatable/dataTables.bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('package/dist/sweetalert2.min.css') }}">
@endsection

@section('title', 'Gambar')

@section('content')
<div class="tambah">
    <a href="{{ url('/gambar/create') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus-square"></i>&nbsp; Tambah Data Baru</a>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Data @yield('title')</strong>
            </div>
            <div class="card-body">
                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th width="200px">ID Gambar</th>
                            <th>Gambar</th>
                            <th width="200px">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($gambar as $value)
                        <tr>
                            <td>{{ $value->id }}</td>
                            <td><img height="150px" src="{{ url('/storage/photos/'.$value->nama_file) }}"></td>
                            <td>
                                <a href="{{ route('gambar.show', $value->id) }}" class="btn btn-primary btn-sm">Rincian</a>
                                <a href="{{ route('gambar.edit', $value->id) }}" class="btn btn-success btn-sm">Ubah</a>
                                <form action="{{ route('gambar.destroy', $value->id) }}" method="POST" id="{{$value->id}}" style="display:inline-block">
                                    @method('DELETE')
                                    {{ csrf_field() }}
                                    <button type="submit" onClick="return confirm('Ingin menghapus data ini?')" class="btn btn-danger btn-sm">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@endsection

@section('script')
<script src="{{ asset('assets/js/lib/data-table/datatables.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/jszip.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/datatables-init.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#bootstrap-data-table-export').DataTable();
    });
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@include('sweet::alert')
@endsection

resources/views/gambar/show.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/lib/datatable/dataTables.bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('package/dist/sweetalert2.min.css') }}">
@endsection

@section('title', 'Gambar')

@section('content')
<div class="tambah">
    <a href="{{ url('/gambar/create') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus-square"></i>&nbsp; Tambah Data Baru</a>
</div>

<div class="row">
    <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <div class="nama">
                            <h3><center>{{$gambar->nama_file}}</center></h3>
                        </div>
                        <tbody>
                            <tr>
                                <th scope="row" width="400px">ID Gambar</th>
                                <td>: {{$gambar->id}} </td>
                            </tr>
                            <tr>
                                <th scope="row" width="400px">Nama File Gambar</th>
                                <td>: {{$gambar->nama_file}} </td>
                            </tr>
                            <tr>
                                <th scope="row">Gambar</th>
                                <td>: <img height="150px" src="{{ url('/storage/photos/'.$gambar->nama_file) }}"> </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</div>
@endsection

@section('script')
<script src="{{ asset('assets/js/lib/data-table/datatables.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/jszip.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/datatables-init.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#bootstrap-data-table-export').DataTable();
    });
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@include('sweet::alert')
@endsection