routes/web.php
<?php
// use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('surat', 'SuratController');

Route::resource('rt', 'RTController');

Route::resource('rw', 'RWController');

Route::resource('penduduk', 'PendudukController');
Route::get('carikota/{id}', 'PendudukController@cariKota')->name('penduduk.carikota');
Route::get('carikecamatan/{id}', 'PendudukController@cariKecamatan')->name('penduduk.carikecamatan');
Route::get('carikelurahan/{id}', 'PendudukController@cariKelurahan')->name('penduduk.carikelurahan');
Route::get('carirw/{id}', 'PendudukController@cariRW')->name('penduduk.carirw');
Route::get('carirt/{id}', 'PendudukController@cariRT')->name('penduduk.carirt');

Route::resource('gambar', 'ImageController');

app/Models/RT.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RT extends Model
{
    protected $table = 'rt';
    protected $primaryKey = 'id_rt';
    protected $fillable = [
        'no_rt', 'nama_rt', 'id_rw'
    ];
    public $timestamps = false;

    /**
     * RT belongs to RW.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function rw()
    {
        return $this->belongsTo(RW::class, 'id_rw', 'id_rw')->with('village');
    }

    /**
     * RT has many Penduduk.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function penduduk()
    {
        return $this->hasMany(Penduduk::class);
    }
}

app/Http/Controllers/RTController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\RW;
use App\Models\RT;
use Alert;

class RTController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rt = RT::all();

        $data = [
            'rt' => $rt
        ];
        
    	return view('rt.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rw = RW::all();
        $data = [
            'rw' => $rw,
        ];
        return view('rt.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except('_token');
        RT::create($data);

        Alert::success('Data berhasil disimpan!', 'Sukses');
        return redirect()->route('rt.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $rt = RT::find($id);
        $rw = RW::where('id_rw', $rt->id_rw)->with('village')->first();
        $data = [
            'rt' => $rt,
            'rw' => $rw,
        ];

        return view('rt.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rt = RT::find($id);
        $rw = RW::where('id_rw', $rt->id_rw)->first();
        $rwother = RW::where('id_rw', '!=', $rw->id_rw)->get();
        $data = [
            'rt' => $rt,
            'rw' => $rw,
            'rwother' => $rwother,
        ];

        return view('rt.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rt = RT::find($id);
        $data = $request->except('_token');
        $rt->update($data);

        Alert::success('Data berhasil diubah!', 'Sukses');
        return redirect()->route('rt.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $rt = RT::find($id);
        $rt->delete();

        Alert::success('Data berhasil dihapus!', 'Sukses');
        return redirect()->route('rt.index');
    }
}

resources/views/rt/create.blade.php
@extends('layouts.master')

@section('title', 'Perangkat RT')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Form Input @yield('title')</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('rt.store') }}" method="post" enctype="multipart/form-data" class="form-horizontal"> 
                    {{ csrf_field() }}
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="no_rt" class=" form-control-label">Nomor RT</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="number" id="no_rt" name="no_rt" value="" placeholder="Maksimal 2 angka" class="form-control" maxlength="2">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="nama_rt" class=" form-control-label">Nama Ketua RT</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text" id="nama_rt" name="nama_rt" value="" class="form-control">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="id_rw" class="form-control-label">Nomor RW</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <select name="id_rw" id="id_rw" class="form-control">
                                <option value="0" selected disabled>Pilih salah satu</option>
                                @foreach ($rw as $value)
                                    <option value="{{ $value->id_rw }}">{{ $value->no_rw }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="menudata">
                        <button type="submit" value="simpan" class="btn btn-primary btn-sm"><i class="fa fa-dot-circle-o"></i> Simpan </button>
                        <a href="{{ route('rt.index') }}" class="btn btn-danger btn-sm"><i class="fa fa-ban"></i> Batal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/rt/edit.blade.php
@extends('layouts.master')

@section('title', 'Perangkat RT')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Form Edit @yield('title')</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{ route('rt.update', $rt->id_rt) }}" method="post" enctype="multipart/form-data" class="form-horizontal"> 
                    @method('put')
                    {{ csrf_field() }}
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="no_rt" class=" form-control-label">Nomor RT</label>
                        </div>
                        <div class="col-12 col-md-9">
                        <input type="number" id="no_rt" name="no_rt" value="{{ $rt->no_rt }}" placeholder="Maksimal 2 angka" class="form-control" maxlength="2">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="nama_rt" class=" form-control-label">Nama Ketua RT</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text" id="nama_rt" name="nama_rt" value="{{ $rt->nama_rt }}" class="form-control">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="id_rw" class="form-control-label">Nomor RW</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <select name="id_rw" id="id_rw" class="form-control">
                                <option value="{{ $rw->id_rw }}" selected>{{ $rw->no_rw }}</option>
                                @foreach ($rwother as $value)
                                    <option value="{{ $value->id_rw }}">{{ $value->no_rw }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="menudata">
                        <button type="submit" value="simpan" class="btn btn-primary btn-sm"><i class="fa fa-dot-circle-o"></i> Simpan </button>
                        <a href="{{ route('rt.index') }}" class="btn btn-danger btn-sm"><i class="fa fa-ban"></i> Batal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/rt/index.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/lib/datatable/dataTables.bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('package/dist/sweetalert2.min.css') }}">
@endsection

@section('title', 'Perangkat RT')

@section('content')
<div class="tambah">
    <a href="{{ url('/rt/create') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus-square"></i>&nbsp; Tambah Data Baru</a>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Data @yield('title')</strong>
            </div>
            <div class="card-body">
                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th width="200px">Nomor RT</th>
                            <th>Nama Ketua RT</th>
                            <th width="200px">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($rt as $value)
                        <tr>
                            <td>{{ $value->no_rt }}</td>
                            <td>{{ $value->nama_rt }}</td>
                            <td>
                                <a href="{{ route('rt.show', $value->id_rt) }}" class="btn btn-primary btn-sm">Rincian</a>
                                <a href="{{ route('rt.edit', $value->id_rt) }}" class="btn btn-success btn-sm">Ubah</a>
                                <form action="{{ route('rt.destroy', $value->id_rt) }}" method="POST" id="{{$value->id_rt}}" style="display:inline-block">
                                    @method('DELETE')
                                    {{ csrf_field() }}
                                    <button type="submit" onClick="return confirm('Ingin menghapus data ini?')" class="btn btn-danger btn-sm">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@endsection

@section('script')
<script src="{{ asset('assets/js/lib/data-table/datatables.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/jszip.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/datatables-init.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#bootstrap-data-table-export').DataTable();
    });
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@include('sweet::alert')
@endsection

resources/views/rt/show.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/lib/datatable/dataTables.bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('package/dist/sweetalert2.min.css') }}">
@endsection

@section('title', 'Perangkat RT')

@section('content')
<div class="tambah">
    <a href="{{ url('/rt/create') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus-square"></i>&nbsp; Tambah Data Baru</a>
</div>

<div class="row">
    <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <div class="nama">
                            <h3><center>{{$rt->nama_rt}}</center></h3>
                        </div>
                        <tbody>
                            <tr>
                                <th scope="row" width="400px">Nomor RT</th>
                                <td>: {{$rt->no_rt}} </td>
                            </tr>
                            <tr>
                                <th scope="row">Nama Ketua RT</th>
                                <td>: {{$rt->nama_rt}} </td>
                            </tr>
                            <tr>
                                <th scope="row">Nomor RW</th>
                                <td>: {{$rw->no_rw}} </td>
                            </tr>
                            <tr>
                                <th scope="row">Nama RW</th>
                                <td>: {{$rw->nama_rw}} </td>
                            </tr>
                            <tr>
                                <th scope="row">Kelurahan</th>
                                <td>: {{$rw->village->name}} </td>
                            </tr>
                            <tr>
                                <th scope="row">Kecamatan</th>
                                <td>: {{$rw->village->district->name}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Kabupaten/Kota</th>
                                <td>: {{$rw->village->district->regency->name}} </td>
                            </tr>
                            <tr>
                                <th scope="row">Provinsi</th>
                                <td>: {{$rw->village->district->regency->province->name}} </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</div>
@endsection

@section('script')
<script src="{{ asset('assets/js/lib/data-table/datatables.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/jszip.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets/js/lib/data-table/datatables-init.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#bootstrap-data-table-export').DataTable();
    });
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@include('sweet::alert')
@endsection